baseURL = "https://www.alexclarizio.com/"
copyright = "Â© Copyright"
googleAnalytics = "UA-123-45"
languageCode = "en-us"
paginate = 10
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "solarized-dark"
summaryLength = 10
theme = "ezhil"
title = "Alex Clarizio's Homepage"
[[menu.main]]
name = "Projects"
url = "/posts/projects"
weight = 5
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
featherIconsCDN = true
mode = "dark"
subtitle = "*Writings for the curious minds.*"
[[params.social]]
icon = "rss"
name = "RSS"
url = "/index.xml"
[taxonomies]
tag = "tags"
